project_name: whoamimcp

env:
  - DOCKER_USERNAME=lajosbencz

builds:
  - binary: whoamimcp
    main: ./cmd/whoamimcp
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - '7'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^chore(deps):'
      - '^test:'
      - '^tests:'

archives:
  - id: whoamimcp
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm}}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

docker_manifests:
  - name_template: '{{ .Env.DOCKER_USERNAME }}/whoamimcp:{{ .Tag }}'
    image_templates:
      - '{{ .Env.DOCKER_USERNAME }}/whoamimcp:{{ .Tag }}-amd64'
      - '{{ .Env.DOCKER_USERNAME }}/whoamimcp:{{ .Tag }}-arm64'
      - '{{ .Env.DOCKER_USERNAME }}/whoamimcp:{{ .Tag }}-armv7'
  - name_template: '{{ .Env.DOCKER_USERNAME }}/whoamimcp:latest'
    image_templates:
      - '{{ .Env.DOCKER_USERNAME }}/whoamimcp:{{ .Tag }}-amd64'
      - '{{ .Env.DOCKER_USERNAME }}/whoamimcp:{{ .Tag }}-arm64'
      - '{{ .Env.DOCKER_USERNAME }}/whoamimcp:{{ .Tag }}-armv7'
  - name_template: '{{ .Env.DOCKER_USERNAME }}/whoamimcp:v{{ .Major }}.{{ .Minor }}'
    image_templates:
      - '{{ .Env.DOCKER_USERNAME }}/whoamimcp:v{{ .Major }}.{{ .Minor }}-amd64'
      - '{{ .Env.DOCKER_USERNAME }}/whoamimcp:v{{ .Major }}.{{ .Minor }}-arm64'
      - '{{ .Env.DOCKER_USERNAME }}/whoamimcp:v{{ .Major }}.{{ .Minor }}-armv7'
  
  # GHCR manifests
  - name_template: 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:{{ .Tag }}'
    image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:{{ .Tag }}-amd64'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:{{ .Tag }}-arm64'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:{{ .Tag }}-armv7'
  - name_template: 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:latest'
    image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:{{ .Tag }}-amd64'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:{{ .Tag }}-arm64'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:{{ .Tag }}-armv7'
  - name_template: 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:v{{ .Major }}.{{ .Minor }}'
    image_templates:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:v{{ .Major }}.{{ .Minor }}-amd64'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:v{{ .Major }}.{{ .Minor }}-arm64'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:v{{ .Major }}.{{ .Minor }}-armv7'

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: buildx.Dockerfile
    image_templates:
      - '{{ .Env.DOCKER_USERNAME }}/whoamimcp:latest-amd64'
      - '{{ .Env.DOCKER_USERNAME }}/whoamimcp:{{ .Tag }}-amd64'
      - '{{ .Env.DOCKER_USERNAME }}/whoamimcp:v{{ .Major }}.{{ .Minor }}-amd64'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:latest-amd64'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:{{ .Tag }}-amd64'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:v{{ .Major }}.{{ .Minor }}-amd64'
    build_flag_templates:
      - '--pull'
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.description=Tiny Go webserver that prints OS information and HTTP request to output'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.url={{.GitURL}}'
      - '--label=org.opencontainers.image.documentation={{.GitURL}}'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--platform=linux/amd64'

  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: buildx.Dockerfile
    image_templates:
      - '{{ .Env.DOCKER_USERNAME }}/whoamimcp:latest-arm64'
      - '{{ .Env.DOCKER_USERNAME }}/whoamimcp:{{ .Tag }}-arm64'
      - '{{ .Env.DOCKER_USERNAME }}/whoamimcp:v{{ .Major }}.{{ .Minor }}-arm64'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:latest-arm64'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:{{ .Tag }}-arm64'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:v{{ .Major }}.{{ .Minor }}-arm64'
    build_flag_templates:
      - '--pull'
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.description=Tiny Go webserver that prints OS information and HTTP request to output'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.url={{.GitURL}}'
      - '--label=org.opencontainers.image.documentation={{.GitURL}}'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--platform=linux/arm64'

  - use: buildx
    goos: linux
    goarch: arm
    goarm: '7'
    dockerfile: buildx.Dockerfile
    image_templates:
      - '{{ .Env.DOCKER_USERNAME }}/whoamimcp:latest-armv7'
      - '{{ .Env.DOCKER_USERNAME }}/whoamimcp:{{ .Tag }}-armv7'
      - '{{ .Env.DOCKER_USERNAME }}/whoamimcp:v{{ .Major }}.{{ .Minor }}-armv7'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:latest-armv7'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:{{ .Tag }}-armv7'
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/whoamimcp:v{{ .Major }}.{{ .Minor }}-armv7'
    build_flag_templates:
      - '--pull'
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.description=Tiny Go webserver that prints OS information and HTTP request to output'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.url={{.GitURL}}'
      - '--label=org.opencontainers.image.documentation={{.GitURL}}'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--platform=linux/arm/v7'
